### PR TITLE
Adding MALA inference

### PR DESCRIPTION
**Pull request by RandomDefaultUser**
This PR adds/will add full MALA inference to the app, and therefore test a few things within the app. 
Currently, there are still a few problems:

- [x] The density format within MALA has changed since the start of this project. Therefore, the `coord_arr` call in line 1071 now crashes - @yyyxam can you take a look? 
- [x] `.out` files are rejected by the uploader, but this is actually a common file ending for QE output files - can we make this work?
- [x] After the density format problem is fixed, I will continue implementing/testing the rest of the inference
- [x] How do we handle model storage? Currently I just put a model into a new folder called `models`, which should work if we host the app ourselves; there may be a better solution, but I am not too experienced with web hosting and may be overlooking something

### CODE REVIEW

**Comment by RandomDefaultUser** [comment]
I figured out the error with the density arrays, so inference runs fully now.

**Comment by mxyyz** [comment]
>     * [x]  `.out` files are rejected by the uploader, but this is actually a common file ending for QE output files - can we make this work?
[25fe517] should fix this, but is a possible security risk for web-hosting (?), since all file-types can now be uploaded. Uploading a .py (crashes+?)restarts the app-instance for example.

>     * [ ]  How do we handle model storage? Currently I just put a model into a new folder called `models`, which should work if we host the app ourselves; there may be a better solution, but I am not too experienced with web hosting and may be overlooking something

_Feel_ like this solution should be fine for web hosting. Server might need a restart after new models are added(?), since `app.py` and `mala_inference.py` would both need editing (
models are stored like this in `app.py`:
`models = [
    {'label': "Solid beryllium at room temperature (298K)", 'value': "Be|298"},
    {'label': "Solid aluminium at room temperature (298K)", 'value': "Al|298"},
    {'label': "Liquid/solid Aluminium at the melting point (933K)", 'value': "Al|933"},
    {'label': "Solid Aluminium from 100K to 933K (100K, editable)", 'value': "Al|[100,933]"},
]`
and in a similar way in `mala_inference.py`
)
-> to find out

**Comment by mxyyz** [comment]
To note: this branch requires both QE and LAMMPS to be installed (as opposed to only LAMMPS on dev)

**Comment by RandomDefaultUser** [comment]
Model storage will not be part of this PR for now, let's first decide how we deploy (i.e. directly for users or centrally within CASUS for outreach).

**Comment by RandomDefaultUser** [comment]
This PR is essentially done, except for a few small cosmetic changes:

- [x] Atom list should be retracted by default
- [x] Settings (on the right) should be expanded by default
- [x] Plot style choice can be removed, since volume doesn't work at the moment (which is not a problem at all); so let's skip the choice and only have "points" for now
- [x] "Band-Energy", "Total-Energy", "Fermi-Energy" -> "Band energy", "Total energy", "Fermi energy" (I looked it up, I would also write "Fermi energy" without the hyphen)
- [x] The loading bar doesn't work correctly at the moment
- [x] There is no option to select only one layer of voxels
- [x] The atoms should be outlined
- [x] There is a bug with the outline checkbox when reducing the opacity

**Comment by mxyyz** [comment]
> * [ ]  Plot style choice can be removed, since volume doesn't work at the moment (which is not a problem at all); so let's skip the choice and only have "points" for now

Done on a surface level -> functionality of saving plot-choice is still there (back end), it's just set to a static "scatter" for now

> * [ ]  The loading bar doesn't work correctly at the moment
> * [ ]  There is no option to select only one layer of voxels
> * [x]  There is a bug with the outline checkbox when reducing the opacity

All 3 need more looking into

**Comment by mxyyz** [comment]
TODOS:

* [x]  The loading bar doesn't work correctly at the moment
* [x]  There is no option to select only one layer of voxels
* [x]  Atom preview on upload is missing the cell (boundaries)

* [x] Optimization

**Pull request merged**
